# Generated by Django 4.2.3 on 2023-07-17 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_foods'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fruitage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fruitage_category', models.CharField(choices=[('leafy-green', 'leafy-green'), ('cruciferous', 'cruciferous'), ('root', 'root'), ('marrow', 'marrow'), ('berries', 'berries')], max_length=100)),
                ('fruitage_type', models.CharField(choices=[('vegetables', 'vegetables'), ('fruits', 'fruits')], max_length=100)),
                ('fruitage_price', models.PositiveIntegerField()),
                ('fruitage_weight', models.CharField(choices=[('500gm', '500gm'), ('1kg', '1kg'), ('2kg', '2kg'), ('3kg', '3kg'), ('4kg', '4kg'), ('5kg', '5kg')], max_length=100)),
                ('fruitage_name', models.CharField(max_length=100)),
                ('fruitage_pic', models.ImageField(upload_to='product_pic/')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Foods',
        ),
    ]
