# Generated by Django 4.2.3 on 2023-07-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_fruitage_delete_foods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruitage',
            name='fruitage_category',
            field=models.CharField(choices=[('leafy-green', 'leafy-green'), ('cruciferous', 'cruciferous'), ('root', 'root'), ('pome', 'pome'), ('berries', 'berries')], max_length=100),
        ),
    ]
